# Generated by Django 5.2.7 on 2025-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_category_celebrity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='is_Private',
            field=models.BooleanField(default=False),
        ),
    ]
