# Generated by Django 5.2.7 on 2025-10-20 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebrities', to=settings.AUTH_USER_MODEL),
        ),
    ]
